### PR TITLE
initial Origami attempt + bump up version

### PR DESCRIPTION
**Pull request by wilsoncai1992**

### CODE REVIEW

**Comment by wilsoncai1992** [comment]
@nhejazi please see the lastest commit facb6ca

**Comment by nhejazi** [comment]
94d4874 introduces changes that allow the folds object (produced by `origami::make_folds`) from the new implementation to be passed to the old implementation. The tests comparing the objects produced by the new and old implementation now pass. Please check it out @wilsoncai1992.

**Comment by wilsoncai1992** [comment]
good!

**Comment by wilsoncai1992** [comment]
lets merge?

**Comment by nhejazi** [comment]
Sure, the implementation based on [`origami`](https://github.com/jeremyrcoyle/origami) now works, so it makes sense to merge. Would you agree that next step should be fixing the problems found by `devtools::check()`? (e.g., documentation and such).

**Pull request merged**
